micronaut:
  application:
    name: socialnet
  server:
    port: 8088
  security:
    enabled: true
    endpoints:
      login:
        enabled: false
    authentication: bearer
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: "${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretAndRememberItShouldBeAtLeast32Characters}"

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: changeme
    driver-class-name: org.postgresql.Driver

jooq:
  datasources:
    default:
      sql-dialect: 'POSTGRES'

flyway:
  datasources:
    default:
      enabled: true